### PR TITLE
Task

### PR DESCRIPTION
**Pull request by chenyukang**
A initial experiment version for task table.

proc seems still a keyword for compiler, 
according to this: https://github.com/rust-lang/rust/pull/19338, it should have been removed.
 I found a bug?  :)

### CODE REVIEW

**Comment by ckkashyap** [comment]
wow ... linking std is working? that is good news.
I looked for a task.c in xv6 but could not find it. What content of xv6 is in task.rs? Or is it just to exercise libstd?

**Comment by chenyukang** [comment]
In xv6, it's named proc.c,  if I named it as task.rs,  then in kernel.rs

```rust
mod proc;
```

the compiler report an error for : "proc is a reserved keyword"

**Comment by ckkashyap** [comment]
btw ... I just realised that libstd is not being linked ....  so it seems we dont need stdlib

**Comment by chenyukang** [comment]
yes, I forgotten remove that line in Makefile.

**Comment by ckkashyap** [comment]
It would be great if you could take up spinlock.rs ... the definition of cpu is pending .... which in turn depends on a few things

**Pull request merged**
